Hello: Hello
PageName: FooBar

WriteAnEntry: Write an entry
Entries: Entries
SubmitEntry: Save
EntryCreated: The entry was created
InvalidInput: Invalid input
Title: Title
Content: Content

CommentsHeading: Comments
NoComments: There are no comments on this post yet
AddCommentHeading: Write comment
LoginToComment: You have to log in in order to comment
Login: Log in
Logout: Log out
AddCommentButton: Add a comment

InfoAlert: Info
EditStaticPages: Edit pages
StaticPageCreated: Page created
SubmitPage: Create
