Default: &defaults
  database: FooBar.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: FooBar_test.sqlite3
  <<: *defaults

Staging:
  database: FooBar_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: FooBar_production.sqlite3
  poolsize: 100
  <<: *defaults
